### ISSUE TITLE
Error on account creation ( first connection) 

### ISSUE THREAD

**Issue by Cracky5457** [zorn-v/nextcloud-social-login#33]
When I try to connect for the first time ( so it's an account creaton ) with my external id oidc provider I got an error 500. If I go back to nextcloud I have my account created and I can use nextcloud.

I don't know if it can be solve here or of it's dependent of the nextcloud/server project

```
Technical details
Remote Address: 127.0.0.1
Request ID: WirC3TlaQxz3oe9SlscW
Type: Error
Code: 0
Message: Call to undefined function OC\imagettfbbox()
File: /Users/myuser/Dev/nextcloud/lib/private/Avatar.php
Line: 260

Trace
#0 /Users/myuser/Dev/nextcloud/lib/private/Avatar.php(176): OC\Avatar->generateAvatar('openid-connect-...', 1024)
#1 /Users/myuser/Dev/nextcloud/lib/private/Avatar.php(86): OC\Avatar->getFile(-1)
#2 /Users/myuser/Dev/nextcloud/lib/private/User/User.php(419): OC\Avatar->get(-1)
#3 /Users/myuser/Dev/nextcloud/apps/dav/lib/CardDAV/Converter.php(146): OC\User\User->getAvatarImage(-1)
#4 /Users/myuser/Dev/nextcloud/apps/dav/lib/CardDAV/Converter.php(56): OCA\DAV\CardDAV\Converter->getAvatarImage(Object(OC\User\User))
#5 /Users/myuser/Dev/nextcloud/apps/dav/lib/CardDAV/SyncService.php(276): OCA\DAV\CardDAV\Converter->createCardFromUser(Object(OC\User\User))
#6 /Users/myuser/Dev/nextcloud/apps/dav/lib/HookManager.php(96): OCA\DAV\CardDAV\SyncService->updateUser(Object(OC\User\User))
#7 /Users/myuser/Dev/nextcloud/lib/private/legacy/hook.php(106): OCA\DAV\HookManager->postCreateUser(Array)
#8 /Users/myuser/Dev/nextcloud/lib/private/Server.php(374): OC_Hook::emit('OC_User', 'post_createUser', Array)
#9 [internal function]: OC\Server->OC\{closure}(Object(OC\User\User), 'v05J7Xwv90XfJDA...')
#10 /Users/myuser/Dev/nextcloud/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
#11 /Users/myuser/Dev/nextcloud/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postCreateUser', Array)
#12 /Users/myuser/Dev/nextcloud/lib/private/User/Manager.php(346): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postCreateUser', Array)
#13 /Users/myuser/Dev/nextcloud/lib/private/User/Manager.php(294): OC\User\Manager->createUserFromBackend('openid-connect-...', 'v05J7Xwv90XfJDA...', Object(OC\User\Database))
#14 /Users/myuser/Dev/nextcloud/apps/sociallogin/lib/Controller/LoginController.php(207): OC\User\Manager->createUser('openid-connect-...', 'v05J7Xwv90XfJDA...')
#15 /Users/myuser/Dev/nextcloud/apps/sociallogin/lib/Controller/LoginController.php(181): OCA\SocialLogin\Controller\LoginController->login('openid-connect-...', Object(Hybridauth\User\Profile))
#16 /Users/myuser/Dev/nextcloud/apps/sociallogin/lib/Controller/LoginController.php(161): OCA\SocialLogin\Controller\LoginController->auth('OCA\\SocialLogin...', Array, 'openid-connect', 'OpenID Connect')
#17 [internal function]: OCA\SocialLogin\Controller\LoginController->customOidc('openid-connect')
#18 /Users/myuser/Dev/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)
#19 /Users/myuser/Dev/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\SocialLogin\Controller\LoginController), 'customOidc')
#20 /Users/myuser/Dev/nextcloud/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\SocialLogin\Controller\LoginController), 'customOidc')
#21 /Users/myuser/Dev/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\SocialLogin...', 'customOidc', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#22 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#23 /Users/myuser/Dev/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#24 /Users/myuser/Dev/nextcloud/lib/base.php(999): OC\Route\Router->match('/apps/sociallog...')
#25 /Users/myuser/Dev/nextcloud/index.php(42): OC::handleRequest()
#26 {main}
```

**Comment by Cracky5457** [comment]
I close I think I just miss a library somewhere and it's not related to Social Login

**Comment by zorn-v** [comment]
You should inslall `php-gd` extention.
`imagettfbbox` is function from it.
