### ISSUE TITLE
Cron and occ won't run when auto redirect is turned on

### ISSUE THREAD

**Issue by hukoeth** [zorn-v/nextcloud-social-login#48]
Hello,
If I set

`'social_login_auto_redirect' => true`

Neither cron.php nor occ run correctly anymore. cron.php just fails silently. occ produces the output below. Pleas let me know if you need any further information.

```
An unhandled exception has been thrown:
Exception: The requested uri() cannot be processed by the script './occ') in /nextcloud/public/lib/private/AppFramework/Http/Request.php:742
Stack trace:
#0 /nextcloud/public/lib/private/AppFramework/Http/Request.php(768): OC\AppFramework\Http\Request->getRawPathInfo()
#1 /nextcloud/public/apps/sociallogin/lib/AppInfo/Application.php(79): OC\AppFramework\Http\Request->getPathInfo()
#2 /nextcloud/public/apps/sociallogin/appinfo/app.php(6): OCA\SocialLogin\AppInfo\Application->register()
#3 /nextcloud/public/lib/private/legacy/app.php(261): require_once('/nextcloud...')
#4 /nextcloud/public/lib/private/legacy/app.php(154): OC_App::requireAppFile(Object(OCA\SocialLogin\AppInfo\Application))
#5 /nextcloud/public/lib/private/legacy/app.php(127): OC_App::loadApp('sociallogin')
#6 /nextcloud/public/lib/private/Console/Application.php(108): OC_App::loadApps()
#7 /nextcloud/public/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /nextcloud/public/occ(11): require_once('/nextcloud...')
#9 {main}
```

**Comment by zorn-v** [comment]
Check v1.9.5
Should be fixed
